const mongoose = require('mongoose');
const Job = require('./models/Job');

const MONGO_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/neurocruit';

const phpJobs = [
  { title: "PHP Backend Developer", description: "<h2>About the Role</h2><p>We are looking for an experienced PHP Backend Developer to join our growing team. You will build and maintain scalable web applications using Laravel.</p><h3>Responsibilities</h3><ul><li>Design and implement RESTful APIs</li><li>Write clean, testable PHP code</li><li>Optimise MySQL queries for performance</li><li>Collaborate with frontend developers</li></ul><h3>Requirements</h3><ul><li>3+ years of PHP development experience</li><li>Strong knowledge of Laravel framework</li><li>Proficiency with MySQL</li></ul>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "hr@phpco.com", contactPhone: "+1-800-100-0001" },
  { title: "Laravel Developer", description: "<h2>Laravel Developer</h2><p>Join our product team and help build robust SaaS features using Laravel and MySQL. You will own the backend layer end-to-end.</p><h3>What You'll Do</h3><ul><li>Develop new Laravel modules</li><li>Write migrations and manage the MySQL schema</li><li>Review pull requests and mentor juniors</li></ul>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "jobs@laravelstudio.io", contactPhone: "+1-800-100-0002" },
  { title: "Full Stack PHP Engineer", description: "<p>We need a versatile engineer comfortable with PHP/Laravel on the backend and basic frontend work. MySQL experience is a must.</p><ul><li>Build and maintain legacy PHP applications</li><li>Migrate monolith features to Laravel</li><li>Write stored procedures and complex MySQL queries</li></ul>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "recruit@fullstackphp.dev", contactPhone: "+1-800-100-0003" },
  { title: "Senior PHP Developer", description: "<h2>Senior PHP Developer</h2><p>We are hiring a Senior PHP Developer to lead a team of 4 engineers. You will be responsible for architecture decisions and code quality.</p><h3>Responsibilities</h3><ul><li>Lead technical design sessions</li><li>Refactor legacy code to Laravel best practices</li><li>Ensure database performance with MySQL</li></ul>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "senior@phpteam.com", contactPhone: "+1-800-100-0004" },
  { title: "PHP API Developer", description: "<p>Build high-performance REST APIs using Laravel. You will work closely with mobile and frontend teams to deliver reliable endpoints.</p><ul><li>Design API contracts</li><li>Implement authentication with Laravel Passport/Sanctum</li><li>Write comprehensive unit tests</li></ul>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "api@phpworks.com", contactPhone: "+1-800-100-0005" },
  { title: "Laravel Backend Engineer", description: "<h2>Laravel Backend Engineer</h2><p>Opportunity to join a fast-growing e-commerce startup. You will own the catalog, ordering, and payment modules built on Laravel.</p><h3>Tech Stack</h3><ul><li>PHP 8.2 + Laravel 11</li><li>MySQL with read replicas</li><li>Redis for caching</li></ul>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "engineering@shopquick.io", contactPhone: "+1-800-100-0006" },
  { title: "PHP CMS Developer", description: "<p>We are looking for a PHP developer with strong CMS experience. You will customise and extend our proprietary Laravel-based CMS platform.</p><ul><li>Develop custom Laravel packages</li><li>Optimise MySQL queries for large content sets</li><li>Implement caching strategies</li></ul>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "cms@contentpro.com", contactPhone: "+1-800-100-0007" },
  { title: "Junior PHP Developer", description: "<h2>Junior PHP Developer</h2><p>Great opportunity for someone early in their career to learn from experienced PHP engineers. We use Laravel and MySQL on all our projects.</p><h3>What We Offer</h3><ul><li>Mentorship from senior developers</li><li>Structured career growth plan</li><li>Exposure to production systems</li></ul>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "hr@jrphp.dev", contactPhone: "+1-800-100-0008" },
  { title: "PHP Ecommerce Developer", description: "<p>We are building the next-generation e-commerce platform with PHP and Laravel. You will implement shopping cart, checkout, and inventory features backed by MySQL.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "tech@ecomshop.com", contactPhone: "+1-800-100-0009" },
  { title: "PHP SaaS Developer", description: "<h2>PHP SaaS Developer</h2><p>Help us build a multi-tenant SaaS product using Laravel's tenancy packages. MySQL per-tenant isolation experience is a plus.</p><ul><li>Implement multi-tenancy patterns</li><li>Build subscription billing with Stripe + Laravel Cashier</li><li>Monitor performance using New Relic</li></ul>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "saas@phpcloud.io", contactPhone: "+1-800-100-0010" },
  { title: "PHP Integration Developer", description: "<p>Connect third-party services (payment gateways, shipping APIs, ERPs) to our Laravel application. You will write robust queue workers and MySQL migrations.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "integrations@connectphp.com", contactPhone: "+1-800-100-0011" },
  { title: "Laravel REST API Engineer", description: "<h2>Laravel REST API Engineer</h2><p>Design and build RESTful APIs consumed by web and mobile clients. Strong understanding of MySQL indexing and query optimisation required.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "api@laravelrest.dev", contactPhone: "+1-800-100-0012" },
  { title: "PHP DevOps Engineer", description: "<p>Manage and deploy PHP/Laravel applications on AWS. You will automate CI/CD pipelines and optimise MySQL RDS instances.</p><ul><li>Set up GitHub Actions for Laravel deployments</li><li>Tune MySQL RDS query performance</li><li>Implement blue-green deployments</li></ul>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "devops@phpops.io", contactPhone: "+1-800-100-0013" },
  { title: "PHP Security Engineer", description: "<h2>PHP Security Engineer</h2><p>Conduct security reviews of our Laravel codebase, identify SQL injection risks in raw MySQL queries, and implement fixes.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "security@phpsec.com", contactPhone: "+1-800-100-0014" },
  { title: "Laravel Package Developer", description: "<p>Create reusable open-source Laravel packages. You will write extensive tests, publish to Packagist, and maintain documentation.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "oss@laravelpkg.dev", contactPhone: "+1-800-100-0015" },
  { title: "PHP Data Engineer", description: "<h2>PHP Data Engineer</h2><p>Build ETL pipelines in PHP that process large datasets and store them in MySQL. Laravel's queue system will be central to the workflow.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "data@phpetl.com", contactPhone: "+1-800-100-0016" },
  { title: "PHP Performance Engineer", description: "<p>Profile and optimise slow PHP/Laravel applications. Tackle N+1 queries, add MySQL indexes, and implement Horizon queue workers.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "perf@fastphp.io", contactPhone: "+1-800-100-0017" },
  { title: "Laravel Mobile Backend Developer", description: "<h2>Laravel Mobile Backend Developer</h2><p>Build the API backend for our iOS and Android apps using Laravel Sanctum for token auth and MySQL for persistence.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "mobile@laravelapi.dev", contactPhone: "+1-800-100-0018" },
  { title: "PHP QA Automation Engineer", description: "<p>Write automated tests for our PHP/Laravel application using PHPUnit and Pest. Set up test database seeding with MySQL fixtures.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "qa@phptests.com", contactPhone: "+1-800-100-0019" },
  { title: "PHP Team Lead", description: "<h2>PHP Team Lead</h2><p>Lead a team of 6 PHP/Laravel engineers. You will run sprint planning, conduct code reviews, and own the MySQL database architecture.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "lead@phpleads.com", contactPhone: "+1-800-100-0020" },
  { title: "Laravel GraphQL Developer", description: "<p>Implement a GraphQL layer on top of our existing Laravel/MySQL backend using Lighthouse PHP. Optimise resolvers and avoid N+1 problems.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "graphql@phpgraph.dev", contactPhone: "+1-800-100-0021" },
  { title: "PHP Reporting Developer", description: "<h2>PHP Reporting Developer</h2><p>Build dynamic reporting dashboards backed by complex MySQL aggregations. Use Laravel's query builder and Chart.js on the frontend.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "reports@phpbiztools.com", contactPhone: "+1-800-100-0022" },
  { title: "Laravel Event-Driven Developer", description: "<p>Design event-sourced systems using Laravel Events, Listeners, and Queues with a MySQL event store. RabbitMQ integration is a bonus.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "events@laravelq.io", contactPhone: "+1-800-100-0023" },
  { title: "PHP Architect", description: "<h2>PHP Architect</h2><p>Define the technical direction for a PHP/Laravel monolith-to-microservices migration. You will design MySQL schemas and service boundaries.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "architect@phparch.com", contactPhone: "+1-800-100-0024" },
  { title: "Laravel Billing Developer", description: "<p>Integrate Stripe, PayPal, and local payment gateways into our Laravel SaaS. Manage subscriptions and invoices stored in MySQL.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "billing@laravelpay.io", contactPhone: "+1-800-100-0025" },
  { title: "PHP Marketplace Developer", description: "<h2>PHP Marketplace Developer</h2><p>Build a multi-vendor marketplace on Laravel. Handle vendor onboarding, commission logic, and MySQL-backed order management.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "marketplace@phpvendor.com", contactPhone: "+1-800-100-0026" },
  { title: "Laravel Notifications Engineer", description: "<p>Implement real-time notifications (email, SMS, push) using Laravel Notifications and Broadcast with a MySQL-backed notification log.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "notify@laravelnotify.dev", contactPhone: "+1-800-100-0027" },
  { title: "PHP Healthcare Developer", description: "<h2>PHP Healthcare Developer</h2><p>Build HIPAA-compliant patient management features using Laravel. Encrypt sensitive MySQL columns and implement audit logging.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "health@phpmed.io", contactPhone: "+1-800-100-0028" },
  { title: "Laravel Search Engineer", description: "<p>Add full-text search to our Laravel app using MySQL full-text indexes and Scout. Later phase will integrate Elasticsearch.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "search@laravelsearch.dev", contactPhone: "+1-800-100-0029" },
  { title: "PHP Legacy Migration Developer", description: "<h2>PHP Legacy Migration Developer</h2><p>Migrate a large CodeIgniter 2 application to Laravel 11. Refactor MySQL stored procedures into Eloquent models.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "legacy@phpupgrade.com", contactPhone: "+1-800-100-0030" },
  { title: "Laravel Internationalisation Developer", description: "<p>Add multi-language support to our Laravel platform. Manage translations in MySQL and integrate with a third-party translation service.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "i18n@laraveli18n.dev", contactPhone: "+1-800-100-0031" },
  { title: "PHP Logistics Developer", description: "<h2>PHP Logistics Developer</h2><p>Build route optimisation and tracking features on Laravel. Store geospatial data in MySQL using spatial data types.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "logistics@phptracker.io", contactPhone: "+1-800-100-0032" },
  { title: "Laravel Admin Panel Developer", description: "<p>Build a feature-rich internal admin panel with Filament or Nova on top of Laravel. MySQL reporting views are required.</p>", skills: ["PHP", "MySQL", "Laravel"], contactEmail: "admin@laraveladmin.dev", contactPhone: "+1-800-100-0033" },
];

const nodeJobs = [
  { title: "Node.js Backend Developer", description: "<h2>Node.js Backend Developer</h2><p>Build scalable microservices using Node.js and Express. Store data in MongoDB using Mongoose ODM.</p><h3>Responsibilities</h3><ul><li>Design RESTful and GraphQL APIs</li><li>Manage MongoDB collections and indexes</li><li>Write unit and integration tests with Jest</li></ul>", skills: ["Node.js", "MongoDB"], contactEmail: "hr@nodeco.io", contactPhone: "+1-800-200-0001" },
  { title: "MEAN Stack Developer", description: "<h2>MEAN Stack Developer</h2><p>Work across the full stack — MongoDB, Express, Angular, Node.js — to deliver product features end-to-end.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "jobs@meanstack.dev", contactPhone: "+1-800-200-0002" },
  { title: "Node.js API Engineer", description: "<p>Design and implement production-grade REST APIs using Node.js. MongoDB will be the primary data store with Redis for caching.</p><ul><li>Build versioned APIs</li><li>Write MongoDB aggregation pipelines</li><li>Implement JWT authentication</li></ul>", skills: ["Node.js", "MongoDB"], contactEmail: "api@nodeapis.dev", contactPhone: "+1-800-200-0003" },
  { title: "Senior Node.js Developer", description: "<h2>Senior Node.js Developer</h2><p>Lead backend architecture decisions for a high-traffic SaaS platform built on Node.js and MongoDB. Own the performance and reliability of core services.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "senior@nodesenior.io", contactPhone: "+1-800-200-0004" },
  { title: "Node.js Microservices Engineer", description: "<p>Design and implement event-driven microservices using Node.js, RabbitMQ, and MongoDB. Kubernetes deployment experience is a plus.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "microservices@nodecloud.io", contactPhone: "+1-800-200-0005" },
  { title: "Node.js Real-Time Developer", description: "<h2>Node.js Real-Time Developer</h2><p>Build real-time features (chat, notifications, live dashboards) using Socket.io on Node.js with MongoDB for message persistence.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "realtime@socketnode.dev", contactPhone: "+1-800-200-0006" },
  { title: "MongoDB Database Engineer", description: "<p>Design and optimise MongoDB schemas, indexes, and aggregation pipelines for a high-volume Node.js platform. Hands-on experience with Atlas preferred.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "dba@mongoteam.io", contactPhone: "+1-800-200-0007" },
  { title: "Node.js DevOps Engineer", description: "<h2>Node.js DevOps Engineer</h2><p>Automate deployment of Node.js services backed by MongoDB Atlas. Set up CI/CD with GitHub Actions and Docker.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "devops@nodeops.io", contactPhone: "+1-800-200-0008" },
  { title: "Node.js Fintech Developer", description: "<p>Build payment processing and reconciliation features on Node.js. Persist transactions in MongoDB with strict write concern settings.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "fintech@nodefin.io", contactPhone: "+1-800-200-0009" },
  { title: "Junior Node.js Developer", description: "<h2>Junior Node.js Developer</h2><p>Start your backend career with us! You will learn Node.js and MongoDB best practices under the guidance of senior engineers.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "hr@nodejunior.dev", contactPhone: "+1-800-200-0010" },
  { title: "Node.js GraphQL Engineer", description: "<p>Implement a GraphQL server using Apollo Server on Node.js with MongoDB as the backing store. Optimise queries to avoid over-fetching.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "graphql@nodegraph.dev", contactPhone: "+1-800-200-0011" },
  { title: "Node.js CLI Tool Developer", description: "<h2>Node.js CLI Tool Developer</h2><p>Build developer-facing CLI tools in Node.js. Persist user config and credentials in a local MongoDB instance.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "tools@nodecli.dev", contactPhone: "+1-800-200-0012" },
  { title: "Node.js IoT Backend Developer", description: "<p>Process IoT device telemetry at scale using Node.js event streams. Store time-series data in MongoDB with time-series collections.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "iot@nodeiot.io", contactPhone: "+1-800-200-0013" },
  { title: "Node.js ETL Developer", description: "<h2>Node.js ETL Developer</h2><p>Build data ingestion pipelines in Node.js that read from external APIs and load data into MongoDB with transformation logic.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "etl@nodepipes.io", contactPhone: "+1-800-200-0014" },
  { title: "Node.js Security Engineer", description: "<p>Audit Node.js applications for security vulnerabilities. Ensure MongoDB deployments follow security best practices (auth, TLS, least privilege).</p>", skills: ["Node.js", "MongoDB"], contactEmail: "security@nodesec.io", contactPhone: "+1-800-200-0015" },
  { title: "Node.js Performance Engineer", description: "<h2>Node.js Performance Engineer</h2><p>Profile Node.js services for CPU and memory bottlenecks. Optimise MongoDB queries and indexes to reduce p99 latency.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "perf@fastnode.io", contactPhone: "+1-800-200-0016" },
  { title: "Node.js Serverless Developer", description: "<p>Build serverless Node.js functions on AWS Lambda and Azure Functions. Use MongoDB Atlas as the persistence layer with connection pooling best practices.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "serverless@nodelambda.dev", contactPhone: "+1-800-200-0017" },
  { title: "Node.js Gaming Backend Developer", description: "<h2>Node.js Gaming Backend Developer</h2><p>Build leaderboards, matchmaking, and session management services using Node.js and MongoDB for a multiplayer mobile game.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "gaming@nodegame.io", contactPhone: "+1-800-200-0018" },
  { title: "Node.js Healthcare Engineer", description: "<p>Develop HIPAA-compliant healthcare APIs in Node.js. Store patient data in encrypted MongoDB collections with field-level encryption.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "health@nodemed.io", contactPhone: "+1-800-200-0019" },
  { title: "Node.js Search Engineer", description: "<h2>Node.js Search Engineer</h2><p>Integrate Atlas Search into a Node.js application to provide fast, relevance-ranked search results from MongoDB data.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "search@nodesearch.dev", contactPhone: "+1-800-200-0020" },
  { title: "Node.js Content Platform Developer", description: "<p>Build a headless CMS backend in Node.js. Store rich content documents in MongoDB with versioning and approval workflows.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "cms@nodecms.io", contactPhone: "+1-800-200-0021" },
  { title: "Node.js Auth Engineer", description: "<h2>Node.js Auth Engineer</h2><p>Implement OAuth2 and SAML SSO flows in Node.js. Store user sessions and refresh tokens in MongoDB with TTL indexes.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "auth@nodeauth.dev", contactPhone: "+1-800-200-0022" },
  { title: "Node.js ML Serving Engineer", description: "<p>Build a model-serving API in Node.js that pre-processes input, calls Python ML models, and logs predictions to MongoDB for monitoring.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "ml@nodeml.io", contactPhone: "+1-800-200-0023" },
  { title: "Node.js Logistics API Developer", description: "<h2>Node.js Logistics API Developer</h2><p>Build route and shipment tracking APIs with Node.js. Use MongoDB geospatial queries for nearest-depot lookups.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "logistics@nodetrack.io", contactPhone: "+1-800-200-0024" },
  { title: "Node.js Team Lead", description: "<p>Lead a team of 5 Node.js engineers. Own MongoDB Atlas cluster management, define coding standards, and run weekly architecture reviews.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "lead@nodeleads.io", contactPhone: "+1-800-200-0025" },
  { title: "Node.js Streaming Developer", description: "<h2>Node.js Streaming Developer</h2><p>Build high-throughput data streaming pipelines using Node.js streams and Kafka. Sink processed events into MongoDB collections.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "stream@nodestream.dev", contactPhone: "+1-800-200-0026" },
  { title: "Node.js Automation Engineer", description: "<p>Write test automation and deployment scripts in Node.js. Seed and validate MongoDB test fixtures as part of the CI pipeline.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "automation@nodeauto.dev", contactPhone: "+1-800-200-0027" },
  { title: "Node.js E-Commerce Backend Developer", description: "<h2>Node.js E-Commerce Backend Developer</h2><p>Build product catalog, cart, and checkout services on Node.js with MongoDB. Experience with change streams for real-time inventory updates is a plus.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "ecom@nodeshop.io", contactPhone: "+1-800-200-0028" },
  { title: "Node.js API Gateway Developer", description: "<p>Build and maintain an API gateway layer in Node.js that routes requests to MongoDB-backed microservices, enforces rate limiting, and logs to Atlas.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "gateway@nodegateway.dev", contactPhone: "+1-800-200-0029" },
  { title: "Node.js Reporting Developer", description: "<h2>Node.js Reporting Developer</h2><p>Write complex MongoDB aggregation pipelines consumed by a Node.js API to power executive dashboards and scheduled email reports.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "reports@nodereport.io", contactPhone: "+1-800-200-0030" },
  { title: "Node.js Blockchain Integration Developer", description: "<p>Build a Node.js service that indexes blockchain events and stores structured data in MongoDB for fast querying by a web UI.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "blockchain@nodechain.dev", contactPhone: "+1-800-200-0031" },
  { title: "Node.js Notification Service Developer", description: "<h2>Node.js Notification Service Developer</h2><p>Design a multi-channel notification service (email, push, SMS) in Node.js with delivery logs stored in MongoDB.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "notify@nodenotify.io", contactPhone: "+1-800-200-0032" },
  { title: "Node.js Admin Tool Developer", description: "<p>Build an internal admin panel API in Node.js with role-based access control backed by MongoDB. Integrate with an existing React frontend.</p>", skills: ["Node.js", "MongoDB"], contactEmail: "admin@nodeadmin.dev", contactPhone: "+1-800-200-0033" },
];

const javaJobs = [
  { title: "Java Backend Developer", description: "<h2>Java Backend Developer</h2><p>Build enterprise-grade backend services using Java and Spring Boot. Design RESTful APIs consumed by web and mobile clients.</p><h3>Requirements</h3><ul><li>3+ years of Java development</li><li>Strong Spring Boot and Spring Data knowledge</li><li>Experience with JPA/Hibernate</li></ul>", skills: ["Java"], contactEmail: "hr@javaco.io", contactPhone: "+1-800-300-0001" },
  { title: "Spring Boot Developer", description: "<h2>Spring Boot Developer</h2><p>Develop and maintain microservices using Spring Boot. You will implement REST APIs, write unit tests with JUnit 5, and manage CI/CD pipelines.</p>", skills: ["Java"], contactEmail: "jobs@springdevs.io", contactPhone: "+1-800-300-0002" },
  { title: "Senior Java Engineer", description: "<p>Lead the design of distributed systems at scale. You will use Java 21 features, Spring Boot 3, and Kafka for event-driven architecture.</p>", skills: ["Java"], contactEmail: "senior@javasenior.dev", contactPhone: "+1-800-300-0003" },
  { title: "Java Microservices Developer", description: "<h2>Java Microservices Developer</h2><p>Design and implement containerised Java microservices with Spring Cloud. Deploy on Kubernetes and monitor with Prometheus and Grafana.</p>", skills: ["Java"], contactEmail: "micro@javamicro.io", contactPhone: "+1-800-300-0004" },
  { title: "Java Full Stack Developer", description: "<p>Work on the full stack — Spring Boot backend, React/Angular frontend. Own features from database schema to UI.</p>", skills: ["Java"], contactEmail: "fullstack@javafull.dev", contactPhone: "+1-800-300-0005" },
  { title: "Java DevOps Engineer", description: "<h2>Java DevOps Engineer</h2><p>Automate build, test, and deployment of Java applications using Maven, Jenkins, and Docker. Optimise JVM startup and memory settings.</p>", skills: ["Java"], contactEmail: "devops@javaops.io", contactPhone: "+1-800-300-0006" },
  { title: "Java Performance Engineer", description: "<p>Profile Java applications with JProfiler and async-profiler. Tune JVM GC settings, fix thread contention, and reduce heap allocations.</p>", skills: ["Java"], contactEmail: "perf@fastjava.io", contactPhone: "+1-800-300-0007" },
  { title: "Junior Java Developer", description: "<h2>Junior Java Developer</h2><p>Start your career with us. You will write Java services under the guidance of senior engineers, fix bugs, and write JUnit tests.</p>", skills: ["Java"], contactEmail: "hr@javajunior.dev", contactPhone: "+1-800-300-0008" },
  { title: "Java Data Engineer", description: "<p>Build ETL pipelines in Java using Apache Spark and Kafka. Transform large datasets and load them into a data warehouse.</p>", skills: ["Java"], contactEmail: "data@javaetl.io", contactPhone: "+1-800-300-0009" },
  { title: "Java Architect", description: "<h2>Java Architect</h2><p>Define the technical roadmap for our Java platform. Design service boundaries, APIs, and data models for a multi-region SaaS product.</p>", skills: ["Java"], contactEmail: "architect@javaarch.dev", contactPhone: "+1-800-300-0010" },
  { title: "Java Security Engineer", description: "<p>Conduct static analysis of Java codebases, fix OWASP top-10 vulnerabilities, and implement Spring Security configurations for OAuth2 and LDAP.</p>", skills: ["Java"], contactEmail: "security@javasec.io", contactPhone: "+1-800-300-0011" },
  { title: "Java Fintech Developer", description: "<h2>Java Fintech Developer</h2><p>Build core banking and payment features in Java with strict ACID guarantees. Experience with FIX protocol or ISO 20022 is a plus.</p>", skills: ["Java"], contactEmail: "fintech@javafin.io", contactPhone: "+1-800-300-0012" },
  { title: "Java Android Developer", description: "<p>Develop native Android applications in Java. Implement complex UI components, background services, and Room database persistence.</p>", skills: ["Java"], contactEmail: "android@javaandroid.dev", contactPhone: "+1-800-300-0013" },
  { title: "Java Automation Test Engineer", description: "<h2>Java Automation Test Engineer</h2><p>Write Selenium and RestAssured automation tests in Java. Maintain the CI test suite and produce coverage reports with JaCoCo.</p>", skills: ["Java"], contactEmail: "qa@javatest.io", contactPhone: "+1-800-300-0014" },
  { title: "Java Integration Developer", description: "<p>Build enterprise integrations using Spring Integration and Apache Camel in Java. Connect ERP, CRM, and third-party APIs.</p>", skills: ["Java"], contactEmail: "integration@javaintegrate.io", contactPhone: "+1-800-300-0015" },
  { title: "Java Healthcare Developer", description: "<h2>Java Healthcare Developer</h2><p>Develop HIPAA-compliant healthcare information systems in Java. Implement HL7 FHIR APIs and integrate with EHR systems.</p>", skills: ["Java"], contactEmail: "health@javamed.io", contactPhone: "+1-800-300-0016" },
  { title: "Java Cloud Engineer", description: "<p>Build and deploy Java services on AWS using ECS Fargate and RDS. Implement Circuit Breaker patterns with Resilience4j.</p>", skills: ["Java"], contactEmail: "cloud@javacloud.io", contactPhone: "+1-800-300-0017" },
  { title: "Java Reactive Developer", description: "<h2>Java Reactive Developer</h2><p>Build reactive, non-blocking services using Project Reactor and Spring WebFlux in Java. Handle high-concurrency use cases with back-pressure.</p>", skills: ["Java"], contactEmail: "reactive@javareactive.dev", contactPhone: "+1-800-300-0018" },
  { title: "Java Reporting Developer", description: "<p>Build complex report generation services in Java using JasperReports and iText PDF. Optimise SQL queries for large result sets.</p>", skills: ["Java"], contactEmail: "reports@javareports.io", contactPhone: "+1-800-300-0019" },
  { title: "Java Telecoms Developer", description: "<h2>Java Telecoms Developer</h2><p>Develop billing and provisioning systems in Java for a major telecoms operator. Experience with DIAMETER or SS7 protocols is a bonus.</p>", skills: ["Java"], contactEmail: "telco@javatelco.io", contactPhone: "+1-800-300-0020" },
  { title: "Java Team Lead", description: "<p>Lead a team of 7 Java engineers. Run sprint ceremonies, review PRs, mentor developers, and own the technical architecture of a billing platform.</p>", skills: ["Java"], contactEmail: "lead@javaleads.io", contactPhone: "+1-800-300-0021" },
  { title: "Java Kafka Developer", description: "<h2>Java Kafka Developer</h2><p>Design Kafka producers and consumers in Java using the Kafka Streams API. Implement exactly-once semantics for financial event streams.</p>", skills: ["Java"], contactEmail: "kafka@javakafka.dev", contactPhone: "+1-800-300-0022" },
  { title: "Java ML Engineer", description: "<p>Integrate Python ML models into a Java serving layer using gRPC and Protocol Buffers. Optimise inference throughput for real-time predictions.</p>", skills: ["Java"], contactEmail: "ml@javaml.io", contactPhone: "+1-800-300-0023" },
  { title: "Java Government Systems Developer", description: "<h2>Java Government Systems Developer</h2><p>Develop secure e-government applications in Java. Clearance required. Experience with digital signature (PKI) standards is preferred.</p>", skills: ["Java"], contactEmail: "gov@javagov.io", contactPhone: "+1-800-300-0024" },
  { title: "Java Supply Chain Developer", description: "<p>Build inventory management and supply chain optimisation features in Java for a global logistics company. SAP integration experience is a plus.</p>", skills: ["Java"], contactEmail: "supply@javasupply.io", contactPhone: "+1-800-300-0025" },
  { title: "Java API Gateway Developer", description: "<h2>Java API Gateway Developer</h2><p>Build and operate an API gateway using Spring Cloud Gateway in Java. Implement rate limiting, authentication, and request transformation.</p>", skills: ["Java"], contactEmail: "gateway@javagateway.dev", contactPhone: "+1-800-300-0026" },
  { title: "Java Retail Systems Developer", description: "<p>Develop POS and inventory systems for a retail chain in Java. Handle real-time synchronisation between stores and central servers.</p>", skills: ["Java"], contactEmail: "retail@javaretail.io", contactPhone: "+1-800-300-0027" },
  { title: "Java Embedded Systems Developer", description: "<h2>Java Embedded Systems Developer</h2><p>Develop Java ME or Android Things applications for embedded devices. Optimise for constrained memory and CPU environments.</p>", skills: ["Java"], contactEmail: "embedded@javaembed.dev", contactPhone: "+1-800-300-0028" },
  { title: "Java CRM Developer", description: "<p>Extend and customise a Salesforce/Java CRM integration. Build automation rules, batch jobs, and reporting APIs in Java.</p>", skills: ["Java"], contactEmail: "crm@javacrm.io", contactPhone: "+1-800-300-0029" },
  { title: "Java Robotics Developer", description: "<h2>Java Robotics Developer</h2><p>Develop navigation and perception software for autonomous robots using Java and ROS2 Java bindings. Sensor fusion experience is valued.</p>", skills: ["Java"], contactEmail: "robotics@javarobot.dev", contactPhone: "+1-800-300-0030" },
  { title: "Java Big Data Engineer", description: "<p>Build Hadoop/Spark data processing jobs in Java at petabyte scale. Optimise Spark SQL queries and manage Yarn cluster resources.</p>", skills: ["Java"], contactEmail: "bigdata@javabig.io", contactPhone: "+1-800-300-0031" },
  { title: "Java ERP Developer", description: "<h2>Java ERP Developer</h2><p>Customise and extend an SAP/Oracle ERP system using Java adapters and BAPIs. Coordinate with finance and operations stakeholders.</p>", skills: ["Java"], contactEmail: "erp@javaerp.io", contactPhone: "+1-800-300-0032" },
  { title: "Java Smart Contract Developer", description: "<p>Write Java smart contract logic for a permissioned Hyperledger Fabric blockchain network. Implement chaincode for asset transfers and audit trails.</p>", skills: ["Java"], contactEmail: "blockchain@javachain.dev", contactPhone: "+1-800-300-0033" },
  { title: "Java Observability Engineer", description: "<h2>Java Observability Engineer</h2><p>Instrument Java services with OpenTelemetry for distributed tracing, metrics, and logs. Set up Grafana dashboards and alert on SLO breaches.</p>", skills: ["Java"], contactEmail: "observability@javaobs.io", contactPhone: "+1-800-300-0034" },
];

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log('Connected to MongoDB');

  console.log('Using seed recruiter (external auth — no DB record needed)');

  const allJobs = [...phpJobs, ...nodeJobs, ...javaJobs].map(j => ({
    ...j,
    recruiterId: 'seed',
    recruiterName: 'Neurocruit Seed',
    recruiterEmail: 'seed@neurocruit.ai',
  }));

  await Job.insertMany(allJobs);
  console.log(`Inserted ${allJobs.length} jobs`);

  await mongoose.disconnect();
  console.log('Done');
}

seed().catch(err => { console.error(err); process.exit(1); });
